### ISSUE TITLE
reset issue with Moodle version 2.8.5 

### ISSUE THREAD

**Issue by Deependrahack** [ajhpark/reset-completion#10]
Got this error message with the moodle 2.8.5 version. When I am going to reset my course completion data.
```
error message{
Coding error detected, it must be fixed by a programmer: The requested cache definition does not exist.core/completion
}
```

**Comment by ajhpark** [comment]
Following may be the solution to the problem (please try with your Moodle version and let me know if it works):
1. Replace the line `cache::make('core', 'completion')->purge();` in `reset_user_completion.php` with the following code:

```
        global $SESSION;

        if (isset($SESSION->completioncache) &&
            array_key_exists($courseid, $SESSION->completioncache)) {
            unset($SESSION->completioncache[$courseid]);
        }
```
