### ISSUE TITLE
Update readme with correct folder name

### ISSUE THREAD

**Issue by luisdev** [ajhpark/reset-completion#11]
I downloaded this plugin from GitHub and got a .zip file called "reset-completion-master.zip". I contains a folder called "reset-completion-master" with the plugin code. When installing the plugin on my Moodle I was unsure if the folder should be renamed to "reset-completion" or "resetcompletion". 

So, two issues with the README.md file:

1. It only includes instructions for getting the code via git clone. It should also describe the installation procedure if you prefer to download the .zip archive from github.com and manually upload it to your Moodle server.
2. The README.md file should explicitly state that the folder should be called "resetcompletion" (not reset-completion). This will avoid any confusion.

**Comment by ajhpark** [comment]
https://github.com/ajhpark/reset-completion/commit/d45e88a66f495f7ad50fea13f18c4880bec58025
