### ISSUE TITLE
Completion check in block is not repeated in backend reset code

### ISSUE THREAD

**Issue by xow** [ajhpark/reset-completion#7]
reset_user_completion.php does not check if the user has completed the course like block_resetcompletion.php does. So a user can remember the url to delete their course early.

**Comment by xow** [comment]
This is still present in 2016110302 because the check is only on the confirmation page. So if someone hits yes it doesn't perform the check again.

However it's unlikely that someone will keep the confirmation page open or save the url for later (and re-type in the sess key) So it's effectively fixed.

**Comment by ajhpark** [comment]
In 2016110800 the check is done after the user hits yes
